### PR TITLE
Do not build io/profiling when only building manuals

### PR DESCRIPTION
**Pull request by wilfwilson**
This should save a few seconds off the "Build manuals" job.

### CODE REVIEW

**Comment by fingolfin** [comment]
Now we can of course do this in the ~100 `CI.yml` files we already have. But perhaps we can also find a way to improve the actions to do this for us "automatically" ?

Specifically, I wonder: do we need `io` and `profiling` to *collect* coverage, or just to submit it (ping @ChrisJefferson) ?

If we only need to submit it, then I would suggest we simply remove those two packages from the default list to build in setup-gap, and instead build them as needed in process-coverage. That way most packages can benefit from this "for free". The exception of course being those which use a custom `GAP_PKGS_TO_BUILD` and currently are forced to include io & profiling in there. But that's "just" ~26, so quite a bit less work.

Then again, we may "want" update all those CI.yml files anyway, to deal with the fact that various actions were renamed... (the old names work, but I guess using both sets of names is a bit confusing...). Note that this can in principle be automated if all we care about is updating the names of the actions; if we also want to switch things to use `gap-actions/setup-gap@v2` then some manual extra work is needed. But on the upside, we can then also simplify some of those CI.yml files, and remove more things from the part which builds the docs... as in this PR: https://github.com/gap-packages/resclasses/pull/19

I guess this here is not the best place for these musings... but I am not sure we have a better one... Slack is a bit too transient and unorganized IMHO, and an issue elsewhere won't be found; the mailing list perhaps... Or perhaps we could try and use https://github.com/gap-system/gap/discussions?

**Comment by ChrisJefferson** [comment]
io and profiling are only needed to submit (and also merge multiple profiles)

**Review by alex-konovalov — CHANGES_REQUESTED** [review]
If we proceed with this, this needs rebasing, and now duplicated in both `.github/workflows/*.yml` files.

**Comment by alex-konovalov** [comment]
Thanks @wilfwilson (haven't seen updated PR).

**Comment by fingolfin** [comment]
Actually I think we should revert this, and instead fix the gap-actions to not install io/profiling by default, instead only building them when/if we process coverage data - see https://github.com/gap-actions/process-coverage/issues/4 and https://github.com/gap-actions/setup-gap/issues/26

**Comment by wilfwilson** [comment]
Fine by me.

**Comment by alex-konovalov** [comment]
So, shall I revert now, if I want to publish its new release?

**Comment by fingolfin** [comment]
It doesn't matter for a release as that doesn't contain the `.github` dir anyway

**Pull request merged**
