### PR TITLE
Move from travis to GH Actions for automated tests

### PR DESCRIPTION
**Pull request by ssiccha**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@ssiccha did this work? I can't see any CI reports, is something to be activated?

**Comment by fingolfin** [comment]
They are only active & visible here once this is merged, for security reasons; in the meantime they run on @ssiccha fork

**Comment by alex-konovalov** [comment]
Thanks for explaining. https://github.com/ssiccha/example/tree/ss/GH-actions still has a README pointing to Travis, but I see that https://github.com/ssiccha/example/actions pass!

**Comment by ssiccha** [comment]
@alex-konovalov I updated the README

**Review by alex-konovalov — APPROVED** [review]
Perfect, thanks @ssiccha !

**Pull request merged**
